### ISSUE TITLE
Quick-save crashes echoes

### ISSUE THREAD

**Issue by smailchali123** [FWGS/hlsdk-xash3d#113]
Im not sure if this problem is with my device because i know echoes need atleast 2gb of ram, but in some areas where my fps tends to drop because alot of details/enemies/ on screen but when i quick-save in those areas the games crashes but the quick-save is there

**Comment by nekonomicon** [comment]
Echoes required ~500MB free memory.
Also, which platform and engine has this trouble.
Are you sure if this trouble HLSDK-related?
