### ISSUE TITLE
Question about reverse engineered mods.

### ISSUE THREAD

**Issue by malortie** [FWGS/hlsdk-xash3d#123]
A few months ago, I found the [open source mods list](https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/opensource-mods.md) and I saw that some mods have been reverse engineered.

Please note that I am not too knowledgeable with reverse engineering, but from my understanding, source code has likely been rewritten by using information from decompiled/disassembled DLLs. Because this reproduces almost if not exactly the experience of the original mods, I have been lately thinking of archiving my HL1 Steampipe patches - precisely the ones for which the original mod has been reverse engineered and has been made cross platform (see ModDB).

Here is the list of reverse engineered mods that have a cross platform release, and for which I had made a Steampipe patch:

- Azure Sheep
- Escape from the darkness
- Half-Life: Visitors
- The Gate
- They Hunger

Please would it be possible to confirm if all mods listed above have been 100% reverse engineered?

**Comment by nekonomicon** [comment]
I'm not sure about The Gate, but all another mods reimplementations must be close to the original on 95-99%.

**Comment by malortie** [comment]
@nekonomicon Thanks. 

In this case, I will play through the mods and compare behaviors with the ones in the original mods.

**Comment by fafa21567** [comment]
Hello and welcome to black mesa

сб, 1 авг. 2020 г., 22:30 Marc-Antoine Lortie <notifications@github.com>:
