### ISSUE TITLE
[Azure Sheep] Map asmap02d crashes due to missing model.

### ISSUE THREAD

**Issue by malortie** [FWGS/hlsdk-xash3d#124]
In the [crossplatform release](https://www.moddb.com/mods/azure-sheeporiginal-remake/downloads/azure-sheep-crossplatform) of Azure sheep, the map asmap02d crashes upon loading due to missing model.

#### Steps to reproduce

In the console, type the following commands:

```
map asmap02d
```

Expected behavior: The map should load as in the original mod.
Actual behavior: An error message occurs:
```
Mod_NumForName: models/gordon.mdl not found
```

#### Possible cause

Below, I believe the model name would need to be changed to **models/freeman.mdl**.

https://github.com/FWGS/hlsdk-xash3d/blob/c6ccf4e7145ddeba387afee421231568977a36f4/dlls/barney.cpp#L811-L812

**Comment by nekonomicon** [comment]
Thanks! Fixed.
