### ISSUE TITLE
[Azure Sheep] Alien slaves do not perform fast beam attacks in easy and medium skill levels.

### ISSUE THREAD

**Issue by malortie** [FWGS/hlsdk-xash3d#125]
In the original Half-Life, alien slaves perform beam attacks faster on skill 'hard' than on easy and medium.

In the original Azure sheep, alien slaves always do the fast beam attack, no matter the skill level. This is also the case for pink alien slaves 'monster_exp_alien_slave'.

In the [crossplatform release](https://www.moddb.com/mods/azure-sheeporiginal-remake/downloads/azure-sheep-crossplatform) of Azure sheep, alien slaves use the same behavior as in Half-Life.

A custom level [bug_alien_slave.zip](https://github.com/FWGS/hlsdk-xash3d/files/5063352/bug_alien_slave.zip) is provided to allow for easier testing and debugging. It includes one normal alien slave 'monster_alien_slave' and one pink alien slave 'monster_exp_alien_slave'.

#### Steps to reproduce

1. In the console, type the following commands:

```
skill 1
map bug_alien_slave
god
```

Expected behavior: Alien slaves should do fast beam attack.
Actual behavior: Alien slaves do the normal beam attack.

2. Disconnect and type the following commands:

```
skill 2
map bug_alien_slave
god
```

Expected behavior: Alien slaves should do fast beam attack.
Actual behavior: Alien slaves do the normal beam attack.

#### Possible cause

The following if statement was probably removed/commented in the original source code.

https://github.com/FWGS/hlsdk-xash3d/blob/c6ccf4e7145ddeba387afee421231568977a36f4/dlls/islave.cpp#L281

**Comment by nekonomicon** [comment]
Thanks! Fixed.
