### ISSUE TITLE
[Half-Life: Visitors] Unable to look around when dead in 1st person.

### ISSUE THREAD

**Issue by malortie** [FWGS/hlsdk-xash3d#126]
In the original Half-Life: Visitors, the player's death is seen from a  'third person' perspective using a view slightly offset above the player, and slowly rotating.

It is still possible to have the player dead and remain in 1st person. This is done via the 'kill' command in the console. When dead in 1st person, the view rotates normally as in the original Half-Life.

In the [crossplatform release](https://www.moddb.com/mods/half-life-visitors/downloads/half-life-visitors-crossplatformwonsteam) of Half-Life: Visitors, when dead in 1st person, the view always remains fixed and the player is unable to look around.

#### Steps to reproduce

1. In the console, type the following commands:

```
map t0a0
kill
```

2. Try and look around.

Expected behavior: View should rotate freely.
Actual behavior: View remains fixed and the player is unable to look around.

**Comment by nekonomicon** [comment]
>When dead in 1st person, the view rotates normally as in the original Half-Life.

And player model will spin too.
We have fix for player view angles on client and server side to avoid model rotating in multiplayer.

**Comment by malortie** [comment]
Thank you for the precisions. I understand now.

I played through the other crossplatform releases and saw that the view angle fix is also present.

In this case, as this is not an issue with the reverse engineered code of Visitors, I will be closing this issue.
