### ISSUE TITLE
[Half-Life: Visitors] Missing effects when shooting at specific textures.

### ISSUE THREAD

**Issue by malortie** [FWGS/hlsdk-xash3d#127]
In the original Half-Life: Visitors, there are additional effects that occur when firing at brushes with specific textures.

These effects include, but might not be limited to: 

- Tiny smoke
- Particles bouncing off wall

In the [crossplatform release](https://www.moddb.com/mods/half-life-visitors/downloads/half-life-visitors-crossplatformwonsteam) of Half-Life: Visitors, these effects are missing.

#### Steps to reproduce

1. In the console, type the following commands:

```
sv_cheats 1
map vis24
impulse 101
```

2. Select the MP5 (9mmAR).
3. Shoot at the concrete walls around your current position.
4. Shoot at the floor you are standing on.

**3 -** Expected behavior: Concrete particles should spawn randomly at the hit location.
    Actual behavior: No concrete particles spawn.

**4 -** Expected behavior: Smoke should spawn at the hit location.
    Actual behavior: No smoke spawns.

Additionally, shooting with the following weapons also casts these effects in the original mod release:

- Glock
- Python
- Shotgun
- Sniper rifle

**Comment by nekonomicon** [comment]
Thanks! Fixed.
