### ISSUE TITLE
[The Gate] Gibbed attack dogs throw alien gibs instead of human gibs.

### ISSUE THREAD

**Issue by malortie** [FWGS/hlsdk-xash3d#128]
In the original The Gate, attack dogs throw human gibs when killed.

In the [crossplatform release](https://www.moddb.com/mods/the-gate/downloads/half-life-the-gate-crossplatform) of The Gate, attack dogs throw alien gibs.

A custom level [gib_dog.zip](https://github.com/FWGS/hlsdk-xash3d/files/5063464/gib_dog.zip) is provided to allow for easier testing and debugging. It includes an attack dog and a knife at player spawn.

#### Steps to reproduce

1. In the console, type the following commands:

```
map gib_dog
```

2. Damage the monster using the knife until it gibs.

Expected behavior: Monster should throw human gibs when killed.
Actual behavior: Monster throws alien gibs when killed.

#### Possible solution

The methods HasHumanGibs and HasAlienGibs return whether or not a monster should emit human/alien gibs. The original mod behavior is probably one of the following cases:

A) The class CHoundeye implements HasHumanGibs

```
BOOL CHoundeye::HasHumanGibs( void )
{
    return TRUE;
}
```

B) There should probably be a check for CLASS_ALIEN_MONSTER in the if statement below.

https://github.com/FWGS/hlsdk-xash3d/blob/e1a96b59f1b214639201bcb8931a100d3a6fa1e3/dlls/combat.cpp#L257-L260

**Comment by nekonomicon** [comment]
Thanks! Fixed.
NOTE: Houndeye's class is equal to CLASS_MACHINE in original mod.
