### ISSUE TITLE
[The Gate] Map gate18 fails to load.

### ISSUE THREAD

**Issue by malortie** [FWGS/hlsdk-xash3d#129]
In the [crossplatform release](https://www.moddb.com/mods/the-gate/downloads/half-life-the-gate-crossplatform) of The Gate, the map gate18 fails to load.

#### Steps to reproduce

In the console, type the following commands:

```
map gate18
```

Expected behavior: The map should load as in the original mod.
Actual behavior: The game goes back to the menu and a message is displayed in the console: 

```
PF_precache_model_I: Model 'sprites/yelflare1.spr' failed to precache because the item count is over the 512 limit.
Reduce the number of brush models and/or regular models in the map to correct this.
```

**Comment by nekonomicon** [comment]
Thanks! Fixed.
