### ISSUE TITLE
Regarding updates of this repository (hlsdk)

### ISSUE THREAD

**Issue by fuzun** [FWGS/hlsdk-xash3d#13]
This repository already contains a lot of fixes if you compare it to 2.3 sdk but as you may know,
- Valve published hlsdk to github and after tons of issue reports and pull requests, It has now many fixes and It has some features which hlsdk-xash3d does not have. Maybe it is good to create a separate branch just for porting them?
- A good developer (Solokiller) who was one of Sven Coop's developers is now making a project called HLEnhanced(https://github.com/SamVanheer/HLEnhanced) and it is so far so good. It is almost a rewrite of vanilla sdk and yet he fixed and implemented bunch of things such as cs 1.6 environment. We can ask him and port them for the sake of this project. This may be very useful for hlsdk-xash3d.
- Porting things from open sourced mods and Regamedll_cs may also be useful.
- Why there are two different hlsdk for xash3d ?
  https://github.com/FWGS/halflife/
  https://github.com/FWGS/hlsdk-xash3d/
  This is very confusing. If xash3d needs a separate one for its own purposes, can't we shrink it? But it would be very good if they get merged. But if this will not happen, please change names or add some description.

**Comment by CrusoeDaWolf** [comment]
I believe the difference between this and the other hlsdk is that this is a VGUI-less one I believe with fixes and such.

As for everything else, I'll wait for one of the devs to have their own input.

**Comment by a1batross** [comment]
ReGameDLL_CS is used in cs16client.

I didn't heard about HLEnhanced, but if it developing over HLSDK
2.4(Valve's halflife repository), we can't use it properly. Client in 2.4
require more work on removing VGUI, while in 2.3 getting vguiless client is
more easier.

I think, we can use some patches from HLEnhanced. But I still don't see why
we need this. Looks like a waste of time.

**Comment by fuzun** [comment]
Considering this is one of the components of xash3d android project, improving things alongside with xash3d core would make hl on android a lot better.
For example mappers can make maps which have rain, snow effects.

I don't see any point why this would be waste of time. Maybe you want to focus on cs ? or promote usage of xashxt (I dont even know if it will be ready for android) or ported spirit of half life ?
I think they cant be stable for a long period. Especially the spirit of half life was not well written. So if you want to promote usage of them instead of this, we can make this a legacy version which does not have features(nightvision, fog, rain, grass) but fixes. And like I said, this fixes may come from hlenhanced or other related open source projects.

Or even can't an all in one sdk called xashsdk be done? It would be very good for development purposes. 
|Xash universal sdk
|->Blueshift
|->Ricochet
|->CS1.6
|->HL
...

**Comment by ryan-sg** [comment]
Just want to note -- xash3d is useful for far more than just android!  I am hoping it becomes THE engine of choice for cross-platform half-life :-)

--happy openbsd xash3d user (amd64!)

**Comment by a1batross** [comment]
@nekonomicon actually backported all fixes from HLSDK 2.4, HLEnchanced and other custom HLSDKs and it's in master branch now! :)
