### ISSUE TITLE
[The Gate] Sniper rifle displays a HUD scope texture when zoomed.

### ISSUE THREAD

**Issue by malortie** [FWGS/hlsdk-xash3d#130]
In the original The Gate, no HUD scope texture is displayed when zooming with the sniper rifle.

In the [crossplatform release](https://www.moddb.com/mods/the-gate/downloads/half-life-the-gate-crossplatform) of The Gate, the sniper rifle displays a scope texture when zoomed in.

#### Steps to reproduce

1. In the console, type the following commands:

```
sv_cheats 1
map t0a0
give weapon_crossbow
```

2. Zoom using the secondary attack.

Expected behavior: No HUD scope texture.
Actual behavior: A HUD scope texture is displayed.

**Comment by nekonomicon** [comment]
It seems scope has check for HEV suit in original mod and I think It's not right behaviour.
So it's actually not a bug.

**Comment by malortie** [comment]
You are right, and when playing the mod in 800x600 and 1024x768, the Sniper rifle displays a scope. The feature is present, but seems unsupported in other resolutions.

Thanks!
