### ISSUE TITLE
[They Hunger] Medkit weapon icon is not displayed on first time pickup.

### ISSUE THREAD

**Issue by malortie** [FWGS/hlsdk-xash3d#132]
Most of the Half-Life weapons display a weapon pickup icon when they are picked up for the first time. 

In the original They Hunger, the medkit weapon displays a pickup icon.

In the [crossplatform release](https://www.moddb.com/mods/they-hunger/downloads/they-hunger-trilogy-crossplatform) of They Hunger, the medkit weapon does not display the pickup icon.

#### Steps to reproduce

In the console, type the following commands:

```
sv_cheats 1
map t0a0
give item_suit
give weapon_th_medkit
```

Expected behavior: Medkit weapon pickup icon shows up
Actual behavior: No weapon pickup icon is displayed

#### Possible solution

The missing behavior would probably have the following form in code:

```cpp
int CWeaponEinarMedkit::AddToPlayer( CBasePlayer *pPlayer )
{
	if( CBasePlayerWeapon::AddToPlayer( pPlayer ) )
	{
		MESSAGE_BEGIN( MSG_ONE, gmsgWeapPickup, NULL, pPlayer->pev );
			WRITE_BYTE( m_iId );
		MESSAGE_END();
		return TRUE;
	}
	return FALSE;
}
```

**Comment by nekonomicon** [comment]
Thanks! Fixed.
