### ISSUE TITLE
[They Hunger] Egon plays runoff sound when holstered.

### ISSUE THREAD

**Issue by malortie** [FWGS/hlsdk-xash3d#133]
In the original They Hunger, the egon 'flamethrower' does not play any sound during holster.

In the [crossplatform release](https://www.moddb.com/mods/they-hunger/downloads/they-hunger-trilogy-crossplatform
) of They Hunger, the runoff sound is played during holster.

#### Steps to reproduce

1. In the console, type the following commands:

```
sv_cheats 1
map t0a0
impulse 101
```

2. Switch to egon.
3. Switch to a different weapon.

Expected behavior: No runoff sound is played.
Actual behavior: Runoff sound is played.

#### Possible cause

It might be possible that the two lines of code were removed/commented in the original source code.

https://github.com/FWGS/hlsdk-xash3d/blob/1ffb009983ec7d36859e559e5dfbf0c478437846/dlls/egon.cpp#L228-L229

**Comment by nekonomicon** [comment]
Thanks! Fixed.
