### ISSUE TITLE
[They Hunger] Gibbed enemy skeletons do not throw gibs.

### ISSUE THREAD

**Issue by malortie** [FWGS/hlsdk-xash3d#135]
In the original They Hunger, both kelly and baby kelly throw human gibs when killed.

In the [crossplatform release](https://www.moddb.com/mods/they-hunger/downloads/they-hunger-trilogy-crossplatform) of They Hunger, both kelly and baby kelly do not throw gibs.

A custom level [gib_kelly.zip](https://github.com/FWGS/hlsdk-xash3d/files/5063953/gib_kelly.zip) is provided to allow for easier testing and debugging. It includes a regular skeleton 'monster_alien_slave', a baby kelly skeleton 'monster_th_babykelly', and an umbrella at player spawn.

#### Steps to reproduce

1. In the console, type the following commands:

```
map gib_kelly
```

2. Damage both monsters using the umbrella until they gib.

Expected behavior: Both monsters should throw human gibs when killed.
Actual behavior: No gib is thrown.

#### Possible solution

According to the reverse engineered source code, there is an additional class: CLASS_SKELETON. Please see the following below:

https://github.com/FWGS/hlsdk-xash3d/blob/1ffb009983ec7d36859e559e5dfbf0c478437846/dlls/cbase.h#L106

https://github.com/FWGS/hlsdk-xash3d/blob/1ffb009983ec7d36859e559e5dfbf0c478437846/dlls/monsters.cpp#L2190

The methods HasHumanGibs and HasAlienGibs return whether or not a monster should emit human/alien gibs. The original mod behavior is probably one of the following cases:

A) The class CISlave implements HasHumanGibs.

```cpp
BOOL CISlave::HasHumanGibs( void )
{
    return TRUE;
}
```

B) There should probably be a check for CLASS_SKELETON in the if statement below.

https://github.com/FWGS/hlsdk-xash3d/blob/1ffb009983ec7d36859e559e5dfbf0c478437846/dlls/combat.cpp#L257-L260

EDIT:

The file agibs.mdl is used for alien gib models. It appears the mod replaces this file with the same content as hgibs.mdl. This adds two additional possible cases:

C) The class CISlave implements HasAlienGibs.

```cpp
BOOL CISlave::HasAlienGibs( void )
{
    return TRUE;
}
```

D) There should probably be a check for CLASS_SKELETON in the if statement below.

https://github.com/FWGS/hlsdk-xash3d/blob/1ffb009983ec7d36859e559e5dfbf0c478437846/dlls/combat.cpp#L271-L276

**Comment by nekonomicon** [comment]
Thanks! Fixed.
NOTE: Original mod does not have CLASS_SKELETON constant and has checks for monster entity names in weapons code.
