### ISSUE TITLE
[Old Engine] MSVC Can't compile server library

### ISSUE THREAD

**Issue by berke33110** [FWGS/hlsdk-xash3d#142]
I have some problems compiling server library in MSVC, it compiles just fine but the game does not load them now as the title says, I'm trying this on the Old Engine of Xash3D and 32-bit build (did not try 64-bit or the New Engine)

But for some reason, compiling on mingw32 does work as intended and has no problems, and if needed:
My Windows SDK is 10.0.18362.0
Platform Toolset is Visual Studio 2019 (v142 build tools)
MSVC Version is 16.7.3
![xash_chop_2020-11-29_02-48-01](https://user-images.githubusercontent.com/22107981/100528394-5fd90380-31ed-11eb-8e3b-6b5094d79f03.png)

**Comment by mittorn** [comment]
check if entry points exported correctly (hl.def must be linked when using MSVC)

**Comment by berke33110** [comment]
Sorry for a long response, I just noticed hl.def wasn't linked (which it should automatically included in CMakeLists anyway) what I did was including hl.def on CMakeLists and rebuilding the server library it automatically added the hl.def directory in Linker/Input/Module Definition File.

I think this issue can be closed now
