### ISSUE TITLE
Failed to compile on VS2013

### ISSUE THREAD

**Issue by CrusoeDaWolf** [FWGS/hlsdk-xash3d#15]
I used cmake and generated the files. Afterwards, I tried to compile the solution. It failed giving me some errors and warnings (P.S Sorry for the mess xP):

> Error	1	error D8021: invalid numeric argument '/Wno-write-strings'	D:\XASHSDLPROJECT\Source Codes\hlsdk-xash3d-master\project-files\cl_dll\cl	client
Warning	2	warning D9025: overriding '/W3' with '/w'	D:\XASHSDLPROJECT\Source Codes\hlsdk-xash3d-master\project-files\dlls\cl	server
Warning	3	warning D9002: ignoring unknown option '-fno-exceptions'	D:\XASHSDLPROJECT\Source Codes\hlsdk-xash3d-master\project-files\dlls\cl	server
Error	4	error C2276: '&' : illegal operation on bound member function expression	D:\XASHSDLPROJECT\Source Codes\hlsdk-xash3d-master\dlls\effects.cpp	413	1	server
Error	5	error C3083: '{ctor}': the symbol to the left of a '::' must be a type	D:\XASHSDLPROJECT\Source Codes\hlsdk-xash3d-master\dlls\effects.cpp	1270	1	server

**Comment by a1batross** [comment]
Don't use CMake in Windows. It isn't supported by our cmake scripts.

Not a bug.

**Comment by fuzun** [comment]
Try this. But I doubt it is backwards compatible with vs2013.

https://github.com/FWGS/hlsdk-xash3d/pull/12
