### ISSUE TITLE
BlueShift: `UTIL_FindEntityInMap: expected {`

### ISSUE THREAD

**Issue by glebm** [FWGS/hlsdk-xash3d#150]
Not sure if this is an issue or simply the case of excessive debug logging.

When running bshift (on `bshift` or `mobile_hacks` branch), the following is logged:

```
[10:11:41] UTIL_FindEntityInMap: expected {
```

This is logged from here:

https://github.com/FWGS/hlsdk-xash3d/blob/4be53d8527eee1d3b56e7f505faba7cefbcb5dac/cl_dll/hud_spectator.cpp#L207-L209

The values in there are:

* `name` is `trigger_camera`.
* `token` is some binary data.

**Comment by nekonomicon** [comment]
Which platform?
Not reproducible for i386 arch.

**Comment by glebm** [comment]
Linux x64

**Comment by nekonomicon** [comment]
Trouble on engine side.

There dangling pointer:
https://github.com/FWGS/hlsdk-xash3d/blob/master/cl_dll/hud_spectator.cpp#L192

**Comment by Idiot64** [comment]
try blueshift: unlocked
did you?

**Comment by Idiot64** [comment]
https://www.moddb.com/games/half-life-blue-shift/downloads/blue-shift-unlocked-v112

**Comment by a1batross** [comment]
Fixed.
