### ISSUE TITLE
Некоторые символы в нике, в scoreboard показываются как другие символы.

### ISSUE THREAD

**Issue by noname946** [FWGS/hlsdk-xash3d#160]
Заметил, что некоторые символы в нике, в scoreboard показываются как другие символы.
Например, вместо " < " показывается " ; ", вместо " > " показывается " : ", вместо " ^ " показывается " ' ".

**Comment by nekonomicon** [comment]
А ты уверен, что проблема не движковая?
Ведь движок обрабатывает эти символы.

**Comment by noname946** [comment]
@nekonomicon Была бы движковая проблема - эти символы путались даже в консоли, но нет, там они показываются корректно.

**Comment by nekonomicon** [comment]
Тем не менее в HL нет поддержки колоркодов, это расширение ксаша.
Ну и рендерятся символы движковым API.
Я рекомендую, прежде, чем здесь что-то репортить, проверять на GoldSource.

**Comment by noname946** [comment]
@nekonomicon К сожалению, но проверить в GoldSource не представляется возможным.

**Comment by noname946** [comment]
@nekonomicon Ладно, раз вы говорите, что текст в scoreboard рендерится движковым API - значит, моя уверенность в том, что это проблема SDK были неверны, я в таком случаю закрою этот issue и открою его уже на этот раз в репе по самому движку.

**Comment by mittorn** [comment]
Возьми машину времени и напиши в поддержку valve где-нибудь в конце 90х про это. Проблема в файлвх халфы
