### ISSUE TITLE
BlueShift: assert failed at ../ref_gl/gl_context.c:126

### ISSUE THREAD

**Issue by daniwenne** [FWGS/hlsdk-xash3d#161]
I'm trying to get blueshift to work on my raspberry pi 4 on arch linux. When I try to start a new game, I get `assert failed at ../ref_gl/gl_context.c:126`. Vanilla half-life works just fine.

**Comment by nekonomicon** [comment]
Obviously, it's not SDK trouble.
Create an issue in FWGS/xash3d-fwgs repository.
