### ISSUE TITLE
[Big lolly] Wrong snark ammo values.

### ISSUE THREAD

**Issue by malortie** [FWGS/hlsdk-xash3d#164]
In the original biglolly release, picking up a snark gives 3 ammo. The maximum carry value appears to be 12.

The following lines:

https://github.com/FWGS/hlsdk-xash3d/blob/cb1b9c6233ca762d4771b40f2a6534f750eb8add/dlls/weapons.h#L116

https://github.com/FWGS/hlsdk-xash3d/blob/cb1b9c6233ca762d4771b40f2a6534f750eb8add/dlls/weapons.h#L153

would need to be changed to this:

```cpp
#define SNARK_MAX_CARRY       12
#define SNARK_DEFAULT_GIVE    3
```

**Comment by nekonomicon** [comment]
Thanks. Fixed.
