### ISSUE TITLE
[Big lolly] Wrong handgrenade ammo values.

### ISSUE THREAD

**Issue by malortie** [FWGS/hlsdk-xash3d#165]
In the original biglolly release, picking up a handgrenade gives 2 ammo. The maximum carry value appears to be 6.

The following lines:

https://github.com/FWGS/hlsdk-xash3d/blob/cb1b9c6233ca762d4771b40f2a6534f750eb8add/dlls/weapons.h#L113

https://github.com/FWGS/hlsdk-xash3d/blob/cb1b9c6233ca762d4771b40f2a6534f750eb8add/dlls/weapons.h#L150

would need to be changed to this:

```cpp
#define HANDGRENADE_MAX_CARRY       6
#define HANDGRENADE_DEFAULT_GIVE    2
```

**Comment by nekonomicon** [comment]
Thanks. Fixed.
