### ISSUE TITLE
How to build it for android ?

### ISSUE THREAD

**Issue by carl1234a** [FWGS/hlsdk-xash3d#168]
I have problem about built it for android first
I write in terminal ndk-build but not working
And i use xash project waf but it's say
OSError: [Errno 2] no such file or directory 'sdk-tools,/build-tools'
How to fix it ? plz plz i wait 5 mouth for waiting to answer it
In addition i run again ndk-build but it's say 
Android Ndk: App_platform not set  defaulting to minium support android-16
Android Ndk:. Your app_build_script point to an unknown file .../jni/Android.mk

**Comment by nekonomicon** [comment]
> And i use xash project waf but it's say
OSError: [Errno 2] no such file or directory 'sdk-tools,/build-tools'

There no recept for waf yet.

https://github.com/FWGS/xash3d-fwgs/issues/140

**Comment by carl1234a** [comment]
Dude i run ndk-build but it's say
Android Ndk: App_platform not set defaulting to minium support android-16
Android Ndk:. Your app_build_script point to an unknown file .../jni/Android.mk

**Comment by nekonomicon** [comment]
> For old engine you need to use ant and android NDK r10e.

**Comment by carl1234a** [comment]
Android Ndk r10e !!!





I use android Ndk r10 without Ndk r10e

**Comment by nekonomicon** [comment]
> Android Ndk: App_platform not set defaulting to minium support android-16

Minimal app_platform for android ndk 10 is android-8.
So you are doing something wrong.

**Comment by a1batross** [comment]
> And i use xash project waf but it's say

You don't need to build Xash3D FWGS itself. We separated mods from engine for reasons.

Building mods isn't going to be easy.  What basically you need to do is to take [mod-sample](https://github.com/FWGS/mod-sample)(there is very simplistic [howto](https://github.com/FWGS/mod-sample/blob/master/HOWTO.txt)) and modify it for your own needs.

**Comment by nekonomicon** [comment]
> Minimal app_platform for android ndk 10 is android-8.
Oh, I forgot...
You need to set APP_PLATFORM in application.mk.
But you can just google it and read official documentation.

**Comment by carl1234a** [comment]
Bruh i wrote it again Ndk-build
But it's say ndk-build :command not found

**Comment by carl1234a** [comment]
Oh sorry i fix it now is working thank you

**Comment by hiIexistlol** [comment]
> Oh sorry i fix it now is working thank you

can we close this, they said it worked so..

**Comment by carl1234a** [comment]
Ok
