### ISSUE TITLE
Mouse does not work properly in GoldSource

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/hlsdk-xash3d#17]
Can't move camera with mouse on default cmake build.

**Comment by FreeSlave** [comment]
Also in fullscreen mode the display is drawn black until I open game menu.

**Comment by CrusoeDaWolf** [comment]
I also have a similar issue with original Xash3D from Uncle Mike!

**Comment by FreeSlave** [comment]
I'm closing it as it was fixed in recent commits.
If you still have some problems with mouse (e.g. it's not as smooth as in original Half-Life, etc.) create another issue.
