### ISSUE TITLE
Could not load library ...\cl_dlls\client.dll

### ISSUE THREAD

**Issue by jorikgrozniy** [FWGS/hlsdk-xash3d#187]
Привет всем. Я скачал дллки из opfor бранча, которые автоматически сбилдил GitHub Actions, но при замене их в игру вылезает след. ошибка:

`Could not load library D:\Half-Life\gearbox\cl_dlls\client.dll`

Я попросил так-же моих друзей протестить дллку, у одного из них работает, у другого нет, прошу помочь разобраться в проблеме. 

Версия игры: 
```
Protocol version 48
Exe version 1.1.2.2 (valve)
Exe build: 13:14:12 Aug 29 2013 (6153)
```

Установка Visual C++ пакетов разных версии (2005-2019) мне не помогла.

Аналогичная ситуация с They Hunger, если я скачаю дллки с последними изменениями из https://github.com/FWGS/hlsdk-xash3d/tree/theyhunger, у меня возникает ровно та же ошибка, НО старая версия Hunger дллок от того же бранча (https://www.moddb.com/mods/they-hunger/downloads/they-hunger-trilogy-crossplatform) работает стабильно без ошибок.

**Comment by mittorn** [comment]
Опять небось рпнтайм штудии прилинковали. Там же сборка опфора очень старая наверно

**Comment by SmileyAG** [comment]
> 
> 
> Опять небось рпнтайм штудии прилинковали. Там же сборка опфора очень старая наверно

Можешь мерджануть во все активные бранчи #185 PR? Он фиксит эту проблему связанную с `Could not load library`, мы только что с @jorikgrozniy затестили.

**Comment by FreeSlave** [comment]
Скорее всего дело в отсутствии vc runtime.
В мастере мы это [исправляли](https://github.com/FWGS/hlsdk-xash3d/commit/136ee78cfd497c0defa47d667ba0e2bf3bf612ef) но в опфор не влили.
