### ISSUE TITLE
Counter-Strike: Condition Zero Deleted Scenes

### ISSUE THREAD

**Issue by SmileyAG** [FWGS/hlsdk-xash3d#189]
Trigger implementations from Solokiller (_changekeyvalue, _sequence): https://github.com/SamVanheer/czeror-sdk

Related to Counter-Strike (such as weapons code):

https://github.com/FWGS/cs16-client/tree/v1.32
https://github.com/s1lentq/ReGameDLL_CS

**Comment by nekonomicon** [comment]
I think It's more related to cs16client/regamedll_cs.

**Comment by SmileyAG** [comment]
> 
> 
> I think It's more related to cs16client/regamedll_cs.

Actually, true. Most of code such as weapons could be taked from ReGameDLL_CS, but it still requires some reverse-engineering stuff, CZ: Deleted Scenes is a single-player game, and there are new entities / weapons / triggers / features (like changes in `CPushable :: Move`, due to which it is impossible to simply push objects, comparing to other HLSDK based games) that are not presented in any of the existing SDKs

**Comment by nekonomicon** [comment]
> Most of code such as weapons could be taked from ReGameDLL_CS

У CS 1.6 и Condition Zero общая кодовая база.
На клиентской части там реализованы 9-way blending, рисование партиклей через particle manager, погодные эффекты, трава, интерфейс на vgui2.
Также на стороне движка именно для Deleted Scenes реализовали скриптовые секвенции, которых не было в WON.
И там сильно не типичный для HLSDK код, включая код оружия.
И я так думаю переносить исходный код CS или какой-нибудь Natural Selection на это SDK затея довольно интересная, но очень бредовая и не стоящая усилий.
Зачем это нужно я не знаю.
И кто вам будет реверсить остатки тем более.

**Comment by a1batross** [comment]
Сложность Deleted Scenes ещё в неясной системе секвенций, которая реализована в движке (она у нас есть и серверная часть игры работает), но используется ровно одной игрой.

**Comment by a1batross** [comment]
А так какие-то костыли под czeror делались в cs16-client, но я уже плохо помню это и к клиенту наврядли когда-нибудь вернусь.
