### ISSUE TITLE
Crash when using func_tank

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/hlsdk-xash3d#19]
```
Program received signal SIGSEGV, Segmentation fault.
0xf7cad86b in CFuncTank::TrackTarget (this=this@entry=0x90a22f8) at func_tank.cpp:487
```

The reason is m_pController->pev becomes null:

```
(gdb) print  m_pController->pev
$1 = (entvars_t *) 0x0
```

I'm not sure how to reproduce it though. It just happens sometimes on my dedicated server.

**Comment by mittorn** [comment]
Check server-rework branch

**Comment by FreeSlave** [comment]
Have not seen this crash for a long time. Can we considered it fixed?

**Comment by mittorn** [comment]
Yes. Now player entity removed only directly before allocating new one and does not change serialnumber at all. It maybe still broken in coop, but coop with saverestore should have more checks in gamedll as engine's changelevel side not designed to work in multiplayer.
