### ISSUE TITLE
Toggling corpse physics?

### ISSUE THREAD

**Issue by Sparktimus** [FWGS/hlsdk-xash3d#190]
Was poking around in the HL1 SDK for a wee bit trying to figure out how I could get the same corpse physics that Sven Coop has and stumbled upon this within the combat.cpp:

	// make the corpse fly away from the attack vector
	pev->movetype = MOVETYPE_TOSS;
	// pev->flags &= ~FL_ONGROUND;
	// pev->origin.z += 2;
	// pev->velocity = g_vecAttackDir * -1;
	// pev->velocity = pev->velocity * RANDOM_FLOAT( 300, 400 );
	
Last four lines are commented out but uncommenting enabled there to be corpse physics similar to Sven's. Why they're disabled is a mystery to me, but I was wondering if it were possible for there to be a cvar of some kind that could toggle this option, or preferably, enable it by default but with the ability to set your own values.

**Comment by Sparktimus** [comment]
I know it's present in every compiled version of the game, but it's simply commented out for some reason. Another mod called Scientist Hunt also had this feature.

**Comment by Sparktimus** [comment]
Since pretty much every Goldsrc lib has that combat.cpp file by default, I wonder if there's a way Xash itself could override that setting globally so you wouldn't have to recompile every lib file you want to use it with

**Comment by Velaron** [comment]
Commenting out code means it's not compiled into the binary, so I don't think there is a good way to do this with existing libraries.

**Comment by FreeSlave** [comment]
The cvar was added to control toggle corpse physics. Should we close the issue?
