### ISSUE TITLE
[Opposing Force] Missing ammo spawn animation for sporelauncher

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/hlsdk-xash3d#227]
There is no ammo spawn (expanding) animation for the Spore Launcher.
Launched Opposing Force with a compiled client and server from the opfor branch of the hlsdk-xash3d repository
https://www.youtube.com/watch?v=bCBo_5Bfod8
Ammo spawns instantly with no animation like the original Opposing Force.

And here is the original Opposing Force launched.
https://www.youtube.com/watch?v=JbYXQ59iFl8

**Comment by FreeSlave** [comment]
I can't reproduce it. For me it plays the animation just fine.
Is there a specific condition to trigger this behavior?
Also do play it on Goldsource or Xash3D?

**Comment by Vladislav4KZ** [comment]
> Also do play it on Goldsource or Xash3D?

Xash3D FWGS 0.20.1 latest beta

**Comment by nekonomicon** [comment]
Need to check such differences under GoldSource anyway.

**Comment by Vladislav4KZ** [comment]
The commit https://github.com/FWGS/hlsdk-xash3d/commit/c4057dc6001cad38bbc8ee2530197751d944164e fixed this animation
