### ISSUE TITLE
[Opposing Force] M249 SAW reload animation is broken

### ISSUE THREAD

**Issue by Vladislav4KZ** [FWGS/hlsdk-xash3d#228]
Only the first part of the animation is displayed

У пулемёта M249 работает только первая часть анимации, не работает анимация закидывания патронов. Пулемёт просто опускается вниз и потом резко возвращается на место заряженным

**Comment by FreeSlave** [comment]
Thanks for reporting. The issue arose from the merge with `master` after we removed the `WeaponTick` function.

**Comment by Vladislav4KZ** [comment]
Thanks, it's fixed

**Comment by Vladislav4KZ** [comment]
I noticed another bug, after emptying the magazine while reloading, no bullets are visible
https://youtu.be/HzwsgmbTang

**Comment by FreeSlave** [comment]
Thanks for reporting. Should be fixed in the new PR.

**Comment by FreeSlave** [comment]
Can we close it now?
