### ISSUE TITLE
Half-Life: Urbicide - Android support

### ISSUE THREAD

**Issue by Qwertyus3D** [FWGS/hlsdk-xash3d#258]
Бомбический мод вышел, с изменённым игровым кодом: https://www.moddb.com/mods/half-life-urbicide/downloads/half-life-urbicide
Прошёл без проблем под ПК-версией FWGS. Предлагаю добавить поддержку мода в стандартный лончер на Андроид. Из отличий заметил только белый HUD и полное отсутствие брони (играем за рядового гражданина, которому под силу воспользоваться только аптечкой, ни HEV-костюм, ни бронежилет не доступны). Оружие и враги стандартные, даже дружественных НПЦ нет (только monster_generic в самом конце).

**Comment by nekonomicon** [comment]
Немного поковырял.
В моде присутствуют новые квары:
```
hud_red
hud_green
hud_blue
cl_autowepswitch
cl_rollangle
cl_rollspeed
cl_bobtilt
```
Цвет худа выставлен через квары

**Comment by FreeSlave** [comment]
Скорее всего основан на halflife-updated, ибо там те же квары есть https://github.com/SamVanheer/halflife-updated/blob/master/cl_dll/hud.cpp#L85

**Comment by FreeSlave** [comment]
@nekonomicon should this issue be closed?

**Comment by nekonomicon** [comment]
If nothing to add
