### ISSUE TITLE
MinGW server binary fails to load

### ISSUE THREAD

**Issue by CrusoeDaWolf** [FWGS/hlsdk-xash3d#55]
So, I got MinGW working and I was able to compile the Xash HLSDK. Client loads fine, but when trying to load up a map, Xash stops and gives an error saying that it couldn't load 'dll\hl.dll'

Here is the engine log:
[engine.log](https://github.com/FWGS/hlsdk-xash3d/files/1866991/engine.log)

At first, engine can load the server binary, but then it runs into a problem (Line 140 in log):
`[2018:04:01|23:05:30] SV_LoadProgs: failed to get address of GiveFnptrsToDll proc`

Any ideas as to what the problem is?

**Comment by mittorn** [comment]
What mingw version do you use?

**Comment by nekonomicon** [comment]
Mingw required linker option `-Wl,--add-stdcall-alias` for some exports.

**Comment by CrusoeDaWolf** [comment]
[engine.log](https://github.com/FWGS/hlsdk-xash3d/files/1868012/engine.log)

Originally, I was using an older version (5.1.0) but after updating MinGW to 6.3.0, Xash refuses to launch client binary now (See log above). Adding `-Wl --add-stdcall-alias` to linker options didn't fix the problem either.

**Comment by FreeSlave** [comment]
Maybe you can make a PR adding step by step instructions on how to build hlsdk with mingw to README.md so other people don't run into the same problems.

**Comment by nekonomicon** [comment]
@FreeSlave, Just needed update CMakeLists.txt for mingw.

**Comment by FreeSlave** [comment]
Yep, that'is even better. If these options are required anyway. So cmake build instructions will be the same across all platforms.

**Comment by CrusoeDaWolf** [comment]
These are the only CMake options I changed:

`CMAKE_CXX_FLAGS=-static-libstdc++`
`CMAKE_SHARED_LINKER_FLAGS=-Wl,--add-stdcall-alias`

**Comment by FreeSlave** [comment]
@CrusoeDaWolf did you have issues like this?
`error: conflicting declaration of ‘int snprintf(char*, size_t, const char*, ...)’ with ‘C’ linkage`

**Comment by CrusoeDaWolf** [comment]
@FreeSlave Nope. I only got a warning related to something being undefined.
