### ISSUE TITLE
Segfault on Mac: g_engfuncs interface is NULL in client.dylib

### ISSUE THREAD

**Issue by x6herbius** [FWGS/hlsdk-xash3d#64]
When I load certain maps (for example, `bounce.bsp`), using the game libraries built from this repo with the Xash3D engine, the game crashes when executing the code in the `LINK_ENTITY_TO_CLASS` macro for `CWorld`.

The exact crash I get is in the client's `cbase.h:222` when executing `operator new`: the `ALLOC_PRIVATE()` macro that resolves to `(*g_engfuncs.pfnPvAllocEntPrivateData)` fails, because the `g_engfuncs` struct in the client is completely zeroed. As far as I can see, `g_engfuncs` isn't referred to from anything within the client library, so I'm a bit confused as to how the system is supposed to work.

The exact details of the crash are as follows:

```
Exception has occurred.
EXC_BAD_ACCESS (code=1, address=0x0)

[Unknown/Just-In-Time compiled code] (Unknown Source:0)
client.dylib!CBaseEntity::operator new(unsigned long, entvars_s*) (/Users/vesper/Desktop/hlsdk-xash3d/dlls/cbase.h:224)
hl.dylib!CWorld* GetClassPtr<CWorld>(CWorld*) (/Users/vesper/Desktop/hlsdk-xash3d/dlls/cbase.h:734)
hl.dylib!::worldspawn(entvars_t *) (/Users/vesper/Desktop/hlsdk-xash3d/dlls/world.cpp:446)
libxash.dylib!SV_AllocPrivateData (/Users/vesper/Desktop/xash3d/engine/server/sv_game.c:984)
libxash.dylib!SV_ParseEdict (/Users/vesper/Desktop/xash3d/engine/server/sv_game.c:4980)
libxash.dylib!SV_LoadFromFile (/Users/vesper/Desktop/xash3d/engine/server/sv_game.c:5071)
libxash.dylib!SV_SpawnEntities (/Users/vesper/Desktop/xash3d/engine/server/sv_game.c:5141)
libxash.dylib!SV_LevelInit (/Users/vesper/Desktop/xash3d/engine/server/sv_init.c:474)
libxash.dylib!SV_Map_f (/Users/vesper/Desktop/xash3d/engine/server/sv_cmds.c:279)
libxash.dylib!Cmd_ExecuteString (/Users/vesper/Desktop/xash3d/engine/common/cmd.c:1082)
libxash.dylib!Cbuf_Execute (/Users/vesper/Desktop/xash3d/engine/common/cmd.c:359)
libxash.dylib!Host_Main (/Users/vesper/Desktop/xash3d/engine/common/host.c:1374)
xash3d!Sys_Start (/Users/vesper/Desktop/xash3d/game_launch/xash.c:161)
xash3d!main (/Users/vesper/Desktop/xash3d/game_launch/xash.c:173)
libdyld.dylib!start (Unknown Source:0)
[Unknown/Just-In-Time compiled code] (Unknown Source:0)
```

This crash can be reproduced by taking the current master branches for the `xash3d` and `hlsdk-xash3d` repos and following these steps:

```
In the xash3d clone:

export CFLAGS="-m32"
export CXXFLAGS="-m32"
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DXASH_VGUI=off ..
make -j8

In the hlsdk-xash3d clone:

export CFLAGS="-m32"
export CXXFLAGS="-m32"
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Debug ..
make -j8

Copy relevant xash3d libraries into the same folder as the xash3d executable
Copy the valve folder from the Mac version of Half Life into this folder
Replace the default .dylibs with those built from the hlsdk-xash3d clone

Run:
export DYLD_LIBRARY_PATH=.
./xash3d -dev 5 -toconsole +map bounce
```

**Comment by mittorn** [comment]
Why server calls  constructor from client library?

**Comment by x6herbius** [comment]
That's part of the reason I'm confused - I don't know. I haven't modified the code in any way.

**Comment by nekonomicon** [comment]
Looks as symbol collisions. I think `-fvisibility=hidden` flag can help, but only in release build.

>EDIT: Looking at the client Cmakelists.txt, it does reference some server files. I guess because operator new is inlined it gets called by the client? I'm not very familiar with how the GoldSrc client/server architecture works though, so I'm not sure I can make a solid diagnosis of what should or shouldn't be happening.

New hlsdk versions (2.2-2.4)uses client weapon prediction and has duplicated code from server on clientside.

**Comment by x6herbius** [comment]
Pull request just got merged, looks like we're all good.
