### ISSUE TITLE
Sounds in momentary_door

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/hlsdk-xash3d#79]
When door starts to return to its initial position the stop sound plays repeatedly.
The stop sound should play once when the door reaches its initial position or the final destination of the whole move.

You can see a bug on maps c2a3a and c2a5 (underwater doors).

**Comment by FreeSlave** [comment]
The issue does not exist in valve hlsdk because the stop sound does not get precached (though if sound is precached somewhere else the bug will come out).
We can either come up with some workaround or don't play sound at all (like in Spirit)

**Comment by FreeSlave** [comment]
There's also another problem (this one exists in valve hlsdk too) - when a door moves to its initial position (after a player stopped using a button), the move sound repeatedly starts and stops leading to repeatedly playing the first sample of the sound.

**Comment by nekonomicon** [comment]
I think trouble in CHAN_STATIC(Repeatable Unkle Mike's mistake).

**Comment by FreeSlave** [comment]
> I think trouble in CHAN_STATIC(Repeatable Unkle Mike's mistake).

CHAN_STATIC is used in valve's sdk too. What's wrong about it?
