### ISSUE TITLE
hev charging sound

### ISSUE THREAD

**Issue by itshamood** [FWGS/hlsdk-xash3d#85]
sometimes when you next a wall and turned ur face a hev charging sound can be heard

**Comment by a1batross** [comment]
Which build? Version? Platform?

**Comment by itshamood** [comment]
Platform: pc version: i dont know but i download it from android github (a version for Windows 32bit) build: the lastest

**Comment by nekonomicon** [comment]
Is It really HLSDK problem?
If not I'm close issue.
