### ISSUE TITLE
Blue shift branch

### ISSUE THREAD

**Issue by MyLittleRobo** [FWGS/hlsdk-xash3d#9]
Consider making Blue Shift branch (and probably for other mods) like you did in halflife repo. But first maybe it makes sense to wait for nekonomicon changes to be merged.

**Comment by nekonomicon** [comment]
I'm create same branch already in my repo.

**Comment by MyLittleRobo** [comment]
@nekonomicon so as your PR was merged, could you PR blue shift too?

**Comment by nekonomicon** [comment]
https://github.com/FWGS/hlsdk-xash3d/pull/11

**Comment by a1batross** [comment]
#11 merged to blueshit branch.
